name: Build Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      attestations: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo build --release
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.4.3
        with:
          subject-path: ./target/release/dpb
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          path: ./target/release/dpb
